Coco-Das/PRIER-BE

.gitignore, src/main/resources/application.properties
> application.properties 파일을 제거해서 비밀번호 노출 방지
*
> application.properties 파일 제거, .gitignore 파일에 추가
*
=> [초기 설정] application.properties 파일 제거

build.gradle, src/main/java/cocodas/prier/aws/AwsS3Service.java, src/main/java/cocodas/prier/board/comment/PostComment.java, src/main/java/cocodas/prier/board/post/post/Post.java, src/main/java/cocodas/prier/board/post/postmedia/PostMedia.java, src/main/java/cocodas/prier/keywords/Keywords.java, src/main/java/cocodas/prier/orders/orderproduct/OrderProduct.java, src/main/java/cocodas/prier/orders/orders/Orders.java, src/main/java/cocodas/prier/point/PointTransaction.java, src/main/java/cocodas/prier/product/Product.java, src/main/java/cocodas/prier/project/comment/ProjectComment.java, src/main/java/cocodas/prier/project/feedback/question/Question.java, src/main/java/cocodas/prier/project/feedback/response/Response.java, src/main/java/cocodas/prier/project/media/ProjectMedia.java, src/main/java/cocodas/prier/project/project/Project.java, src/main/java/cocodas/prier/project/project/dto/ProjectDto.java, src/main/java/cocodas/prier/project/tag/projecttag/ProjectTag.java, src/main/java/cocodas/prier/project/tag/tag/Tag.java, src/main/java/cocodas/prier/quest/Quest.java, src/main/java/cocodas/prier/user/UserRepository.java, src/main/java/cocodas/prier/user/Users.java
> 사진 및 동영상 S3를 이용해 저장가능, 연관관계 매핑 올바르게 수정
*
> S3 의존성 추가했고, 연관관계 매핑에서 @JoinColumn이 빠져서 추가 및 모든 엔티티에 @Getter 추가
*
> 연관관계 매핑 다시한번 확인해줘도 좋을듯
*
=> AWS S3 설정 및 연관관계 매핑 수정

src/main/java/cocodas/prier/board/comment/PostComment.java, src/main/java/cocodas/prier/board/post/post/Post.java, src/main/java/cocodas/prier/board/post/postmedia/PostMedia.java, src/main/java/cocodas/prier/keywords/Keywords.java, src/main/java/cocodas/prier/orders/orderproduct/OrderProduct.java, src/main/java/cocodas/prier/orders/orders/Orders.java, src/main/java/cocodas/prier/point/PointTransaction.java, src/main/java/cocodas/prier/product/Product.java, src/main/java/cocodas/prier/project/comment/ProjectComment.java, src/main/java/cocodas/prier/project/feedback/question/Question.java, src/main/java/cocodas/prier/project/feedback/response/Response.java, src/main/java/cocodas/prier/project/media/ProjectMedia.java, src/main/java/cocodas/prier/project/project/Project.java, src/main/java/cocodas/prier/project/tag/projecttag/ProjectTag.java, src/main/java/cocodas/prier/project/tag/tag/Tag.java, src/main/java/cocodas/prier/quest/Quest.java, src/main/java/cocodas/prier/user/Users.java
> 서버 껐다가 키면 id가 50씩 늘어나는 문제 수정, 예약어로 인해 Users 테이블이 생성되지 않는 문제 수정
*
> 서버 껐다가 키면 id가 50씩 늘어나지 않도록 하기위해 GeneratedValue 수정, rank가 MySQL 예약어라서 rank -> tier로 수정
*
=> build : GeneratedValue를 AUTO -> IDENTITY 수정, Users 엔티티의 rank -> tier 수정

src/main/java/cocodas/prier/aws/AwsS3Service.java, src/main/java/cocodas/prier/product/Product.java, src/main/java/cocodas/prier/product/ProductController.java, src/main/java/cocodas/prier/product/ProductRepository.java, src/main/java/cocodas/prier/product/ProductService.java, src/main/java/cocodas/prier/product/dto/CreateProductForm.java, src/main/java/cocodas/prier/product/dto/ProductForm.java, src/main/java/cocodas/prier/product/dto/ProductResponseDto.java, src/main/java/cocodas/prier/product/media/ProductMedia.java, src/main/java/cocodas/prier/product/media/ProductMediaRepository.java, src/main/java/cocodas/prier/project/project/ProjectController.java, src/main/java/cocodas/prier/project/project/ProjectService.java, src/main/java/cocodas/prier/project/project/dto/CreateProjectForm.java
>  S3 업로드 및 삭제 기능 구현, 상품 등록시 이미지 하나 등록 가능
*
> AWS 서비스에 파일 삭제 추가
상품 미디어 엔티티 추가
상품 등록시 상품 이미지도 등록 가능
상품 삭제시 S3에서도 같이 삭제
상품과 상품 이미지는 일대일 관계로 매핑
S3 업로드 및 삭제 정상작동
*
=> feat : AWS 서비스 수정, 상품 이미지 엔티티 추가, 상품 등록, 삭제, 상품 정보 업데이트 구현

build.gradle, src/main/java/cocodas/prier/user/KakaoService.java, src/main/java/cocodas/prier/user/UserController.java, src/main/java/cocodas/prier/user/UserRepository.java, src/main/java/cocodas/prier/user/UserService.java, src/main/java/cocodas/prier/user/Users.java, src/main/java/cocodas/prier/user/dto/response/KakaoTokenResponseDto.java, src/main/java/cocodas/prier/user/dto/response/KakaoUserInfoResponseDto.java, src/main/resources/templates/home.html, src/main/resources/templates/login.html
* 카카오 로그인 구현했음
* 카카오 로그인
* 카카오 로그인
=> feat: 카카오 로그인 구현 및 유저 정보 h2 DB에 저장

src/main/java/cocodas/prier/config/SecurityConfig.java, src/main/java/cocodas/prier/user/UserController.java, src/main/java/cocodas/prier/user/dto/response/LoginSuccessResponse.java, src/main/java/cocodas/prier/user/kakao/KakaoService.java, src/main/java/cocodas/prier/user/kakao/jwt/token/RefreshTokenService.java, src/main/java/cocodas/prier/user/kakao/jwt/token/Token.java, src/main/resources/templates/home.html
* jwt token
* redis에 jwt refresh token 저장
* home에 일단 정보 보여줄 수 있게 id, email, nickname, access token, refresh token dto로 만들어서 보냄
* dto는 나중에 바꿔야 할 듯?
=> feat: Jwt refresh token

src/main/java/cocodas/prier/point/PointTransaction.java, src/main/java/cocodas/prier/point/PointTransactionController.java, src/main/java/cocodas/prier/point/PointTransactionRepository.java, src/main/java/cocodas/prier/point/PointTransactionService.java, src/main/java/cocodas/prier/point/dto/PointPurchaseRequest.java, src/main/java/cocodas/prier/point/dto/PointRechargeRequest.java, src/main/java/cocodas/prier/point/dto/PointTransactionDTO.java
* 포인트 관련 기능 구현
* point 폴더에 dto (PointPurchaseRequest, PointRechargeRequest, PointTransactionDTO) 생성
* PointTransactionService, PointTransactionController 추가
* PointTransaction 수정중 (balance는 제거 필요, 아직 안 함)
1) 연관관계 수정 (`OneToOne` -> `ManyToOne`)
2) `@Enumerated(EnumType.STRING`) 추가
* Users 수정 후 수정해야 할 것들 남아있음, 주석에 달아놓았음
=> feat: 현재 포인트 조회, 트랜잭션 내역 조회, 포인트 충전 (POINT_CHARGE) 기능 구현

src/main/java/cocodas/prier/quest/Quest.java, src/main/java/cocodas/prier/quest/QuestController.java, src/main/java/cocodas/prier/quest/QuestRepository.java, src/main/java/cocodas/prier/quest/QuestService.java, src/main/java/cocodas/prier/quest/QuestStatus.java, src/main/java/cocodas/prier/user/Users.java
* Quest CRUD
* 기존에 작성한 QuestStatus 삭제 - 이렇게 하면 한 유저당 데이터를 3개 만들어야 함
* 그래서 하나로 나갈 수 있게 구현
* 댓글이랑 피드백 완료되어야 퀘스트도 완료 가능
* 그래서 1번 퀘스트 하는 거랑 기본 틀만 잡아 놓음
* QuestStatus 삭제
=> feat: Quest CRUD 일부 구현

src/main/java/cocodas/prier/config/SecurityConfig.java, src/main/java/cocodas/prier/user/Users.java, src/main/java/cocodas/prier/user/kakao/KakaoService.java, src/main/java/cocodas/prier/user/kakao/jwt/JwtTokenProvider.java, src/main/java/cocodas/prier/user/kakao/jwt/UserAuthentication.java
* jwt token에 kakao access token을 추가함으로써 추후 로그인 시 사용하기 위함
* 로그인할 때 마지막 로그인 시점 저장
* jwt token에 kakao access token을 추가
* Users에 updateLastLoginAt 추가
* SecurityConfig에 localhost:3000 추가
*
=> feat: fix: chore: jwt token 에 kakao access token 추가

src/main/java/cocodas/prier/point/PointTransactionService.java
* 피드백 기간 연장 기능 구현
* 피드백 기간 연장 기능을 포인트트랜잭션서비스에 추가하였다.
* 프로젝트 컨트롤러에 피드백 기간 연장 엔드포인트를 추가해야 한다.
=> feat: 피드백 기간 연장 (FEEDBACK_EXTENSION) 기능 PointTransactionService 추가

src/main/java/cocodas/prier/user/kakao/jwt/JwtAuthenticationFilter.java, src/main/java/cocodas/prier/user/kakao/jwt/JwtTokenProvider.java
* kakao access token 추가한 것을 반영하지 않아서 반영해줌
* JwtAuthenticationFilter
*
=> fix: JwtAuthenticationFilter 오류 수정

src/main/java/cocodas/prier/point/PointTransactionService.java
* PointTransactionService 잘못된 코드 수정 및 추가
*
*
=> chore: PointTransactionService 잘못된 코드 수정 및 추가

src/main/java/cocodas/prier/point/PointTransaction.java, src/main/java/cocodas/prier/point/PointTransactionRepository.java, src/main/java/cocodas/prier/point/PointTransactionService.java
* PointTransaction nullable 추가
* PointTransactionRepository 수정
* 위 사항 수정하고 추가적으로
* Users와 매핑 @ManyToOne(optional = false) 추가
*
=> chore: PointTransaction nullable 추가, PointTransactionRepository 수정

src/main/java/cocodas/prier/point/PointTransaction.java, src/main/java/cocodas/prier/point/PointTransactionService.java, src/main/java/cocodas/prier/user/Users.java
* 피드백 연장 포인트 수정
* Users에 updateBalance 수정
* Users에 updateBalance -> 초기값 0으로 설정하고, amount에 따라 변동되도록 설정
* 피드백 연장 포인트 회의 결과에 따라 주당 250으로 설정
* pointTransaction에 있는 balance는 변동 직후 잔액, users에 있는 balance는 현재 잔액 (가장 최신 version) 으로 수정
*
=> chore: 피드백 연장 포인트 수정, Users에 updateBalance 수정

src/main/java/cocodas/prier/user/Rank.java, src/main/java/cocodas/prier/user/Users.java
* Users 테이블에서 Rank 를 rookie 로 defaultValue 값 설정했습니다
* Users
-
=> feat: Rank 기본값 설정하기

src/main/java/cocodas/prier/project/feedback/question/Question.java, src/main/java/cocodas/prier/project/feedback/question/QuestionService.java, src/main/java/cocodas/prier/project/media/ProjectMedia.java, src/main/java/cocodas/prier/project/media/ProjectMediaService.java, src/main/java/cocodas/prier/project/project/Project.java, src/main/java/cocodas/prier/project/project/ProjectController.java, src/main/java/cocodas/prier/project/project/ProjectService.java, src/main/java/cocodas/prier/project/project/dto/ProjectForm.java, src/main/java/cocodas/prier/project/tag/projecttag/ProjectTag.java, src/main/java/cocodas/prier/project/tag/projecttag/ProjectTagRepository.java, src/main/java/cocodas/prier/project/tag/projecttag/ProjectTagService.java, src/main/java/cocodas/prier/project/tag/tag/Tag.java, src/main/java/cocodas/prier/project/tag/tag/TagRepository.java, src/main/java/cocodas/prier/project/tag/tag/TagService.java
=> feat: Project 생성 및 기타 기능 구현

src/main/java/cocodas/prier/user/Users.java
=> fix : rank -> tier로 수정

src/main/java/cocodas/prier/user/UserController.java
* UserController 메서드 명 변경
* UserController
-
=> fix: UserController 메서드 명 수정

src/main/java/cocodas/prier/project/tag/projecttag/ProjectTagService.java, src/main/java/cocodas/prier/project/tag/tag/TagService.java
*
> tag 안들어가는 문제는 json 잘못 작성했었음, 트랜잭션 설정
*
*
=> fix : 트랜잭션 설정

src/main/java/cocodas/prier/project/feedback/question/Question.java, src/main/java/cocodas/prier/project/feedback/question/QuestionService.java, src/main/java/cocodas/prier/project/media/ProjectMediaService.java, src/main/java/cocodas/prier/project/project/ProjectController.java, src/main/java/cocodas/prier/project/project/ProjectService.java, src/main/java/cocodas/prier/project/tag/projecttag/ProjectTagRepository.java, src/main/java/cocodas/prier/project/tag/projecttag/ProjectTagService.java
*
>  프로젝트 삭제 구현(삭제 시 연관된 미디어, 질문 삭제되고, 태그와 관계 매핑되어있는 데이터도 삭제. 태그는 삭제되지 않음)
태그는 다른 프로젝트랑도 연결될 수 있기 때문에 삭제되면 안됨. (외래키가 보호해주는 듯)
프로젝트 업데이트 구현중..
미디어 업데이트랑 질문 업데이트 구현하면 됨. 태그 업데이트는 구현 완료
*
*
=> feat : 프로젝트 삭제 구현

src/main/java/cocodas/prier/product/ProductService.java, src/main/java/cocodas/prier/project/media/ProjectMediaService.java, src/main/java/cocodas/prier/project/project/ProjectService.java, src/main/java/cocodas/prier/project/tag/projecttag/ProjectTagRepository.java, src/main/java/cocodas/prier/project/tag/projecttag/ProjectTagService.java
=> fix : 프로젝트 삭제 시 S3에서도 삭제되도록 수정

src/main/java/cocodas/prier/orders/orderproduct/OrderProduct.java, src/main/java/cocodas/prier/product/ProductService.java
* OrderProduct 개발
* OrderProduct에 unitPrice, totalPrice를 추가하여 가격 변경에 대한 기록을 유지하도록 함 (이후에 상품 가격이 변해도 주문했던 시점의 가격 정보만 반영하도록)
* ProductService에 createOrderProduct (주문 내역 기록)을 추가함
*
=> feat: OrderProduct에 메소드 및 컬럼 추가, ProductService에 주문내역 기록 추가

src/main/java/cocodas/prier/orders/orderproduct/dto/OrderProductDto.java, src/main/java/cocodas/prier/orders/orders/OrderService.java, src/main/java/cocodas/prier/orders/orders/Orders.java, src/main/java/cocodas/prier/point/PointTransactionService.java, src/main/java/cocodas/prier/product/ProductController.java, src/main/java/cocodas/prier/product/ProductService.java
* 상품 구매 기능 구현
* Orders 엔티티 수정
* OrderService 추가
* ProductController에 상품 구매처리 추가 
*
=> feat: 상품 구매 기능 구현중

src/main/java/cocodas/prier/user/UserController.java, src/main/java/cocodas/prier/user/dto/response/LoginSuccessResponse.java, src/main/java/cocodas/prier/user/kakao/KakaoService.java
* 원래 dto에 다른 정보도 있었는데 jwt 토큰만 주게 하고 싶음
* dto에 jwt 토큰만 줄 수 있게 변경
*
=> fix: jwt 토큰만 줄 수 있게 dto 변경

build.gradle, src/main/java/cocodas/prier/user/UserService.java
* 마이페이지 수정하기에 @Transactional 추가
* UserService
=> fix: 수정하기 Transactional 추가

src/main/java/cocodas/prier/user/dto/response/LoginSuccessResponse.java, src/main/java/cocodas/prier/user/kakao/KakaoService.java
* dto에 kakaoAccessToken 추가
* dto에 kakaoAccessToken 추가
*
=> fix: dto에 kakaoAccessToken 추가

build.gradle, src/main/java/cocodas/prier/config/SecurityConfig.java, src/main/java/cocodas/prier/user/UserController.java
=> fix: 로그인 기능 수정

src/main/java/cocodas/prier/project/project/ProjectController.java, src/main/java/cocodas/prier/project/project/ProjectService.java
*
> 피드백 받을수 있는 기간 연장 구현 / 프로젝트 삭제, 수정 시 유저 확인 후 실행하도록 수정
* 1주에 250포인트 맞지? ㅋㅋ
=> feat : 피드백 받을수 있는 기간 연장 구현 / 프로젝트 삭제, 수정 시 유저 확인 후 실행하도록 수정

src/main/java/cocodas/prier/point/PointTransactionController.java, src/main/java/cocodas/prier/point/PointTransactionService.java
* jwt에 맞추어 PointTransaction 수정
* 상품 등록, 조회도 잘 올라가는 것 확인했음
* PointTransactionController 모두 테스트 완료. 성공
=> fix: PointTransactionController 모두 테스트 완료

src/main/java/cocodas/prier/orders/orderproduct/OrderProduct.java, src/main/java/cocodas/prier/orders/orders/Orders.java, src/main/java/cocodas/prier/product/ProductController.java, src/main/java/cocodas/prier/product/ProductService.java
* #47에 따라 포인트 차감-PRODUCT_PURCHASE 해당하는 코드 모두 수정
* #47에 따라 포인트 차감-PRODUCT_PURCHASE 해당하는 코드 모두 수정
* 그리고 은진이와 상품 주문은 하나씩만 하도록 했었는데 이걸 까먹고 코드를 짜서 상품은 무조건 하나씩만 주문 가능하도록 수정함. 
*
=> refactor: PR #47에 따라 포인트 차감-PRODUCT_PURCHASE 해당하는 코드 모두 수정

src/main/java/cocodas/prier/project/project/Project.java, src/main/java/cocodas/prier/project/project/ProjectService.java
=> fix : 피드백 기간연장 포인트 트랜잭션과 연결

src/main/java/cocodas/prier/product/ProductController.java
* ProductController에서 하나씩 상품 구매하도록 수정 및 테스트 완료
* ProductController에서 하나씩 상품 구매하도록 수정 및 테스트 완료
*
=> refactor: ProductController에서 하나씩 상품 구매하도록 수정 및 테스트 완료

src/main/java/cocodas/prier/user/UserController.java
* 카카오 로그인 프론트와 연동 성공
* UserController 에 한해서 CrossOrigin 설정 완료
=> test: 카카오 로그인 프론트와 연결 성공

src/main/java/cocodas/prier/project/comment/ProjectComment.java, src/main/java/cocodas/prier/project/comment/ProjectCommentController.java, src/main/java/cocodas/prier/project/comment/ProjectCommentRepository.java, src/main/java/cocodas/prier/project/comment/ProjectCommentService.java, src/main/java/cocodas/prier/project/comment/dto/CommentDto.java, src/main/java/cocodas/prier/project/comment/dto/CommentForm.java, src/main/java/cocodas/prier/project/project/Project.java, src/main/java/cocodas/prier/project/project/ProjectController.java, src/main/java/cocodas/prier/project/project/ProjectService.java, src/main/java/cocodas/prier/project/project/dto/ProjectDetailDto.java
*
* 프로젝트 댓글 CRUD 구현 / 프로젝트 별점 구현
*  댓글다는건 퀘스트랑도 연결되야할듯.
=> feat : 프로젝트 댓글 CRUD 구현 / 프로젝트 별점 구현

src/main/java/cocodas/prier/user/UserController.java
* 테스트용이 필요함
* UserController에 테스트용 추가 - login.html로 로그인 하면 jwt 토큰 얻을 수 있음
*
=> test: 개발할 때 jwt 토큰 필요해서 테스트용 추가

build.gradle, src/main/java/cocodas/prier/board/post/PostController.java, src/main/java/cocodas/prier/board/post/post/Category.java, src/main/java/cocodas/prier/board/post/post/Post.java, src/main/java/cocodas/prier/board/post/post/PostRequestDto.java, src/main/java/cocodas/prier/board/post/post/PostService.java, src/main/java/cocodas/prier/board/post/post/request/PostRequestDto.java, src/main/java/cocodas/prier/user/Rank.java, src/main/java/cocodas/prier/user/Users.java
* ENUM 값 수정, 게시글 수정하는 부분 코드 변경
* ENUM, PostService
=> fix: ENUM 값 수정, 게시글 수정

src/main/java/cocodas/prier/project/project/ProjectController.java, src/main/java/cocodas/prier/project/project/ProjectRepository.java, src/main/java/cocodas/prier/project/project/ProjectService.java
* 내 프로젝트 조회 추가 및 조회
* 내 프로젝트 조회 추가 및 조회시 최신순, 등록순, 진행중인 프로젝트로 필터 가능
*
=> feat : 내 프로젝트 조회 추가 및 조회시 최신순, 등록순, 진행중인 프로젝트로 필터 가능

src/main/java/cocodas/prier/board/comment/PostComment.java, src/main/java/cocodas/prier/board/comment/PostCommentController.java, src/main/java/cocodas/prier/board/comment/PostCommentRepository.java, src/main/java/cocodas/prier/board/comment/PostCommentService.java, src/main/java/cocodas/prier/board/comment/request/PostCommentRequestDto.java, src/main/java/cocodas/prier/board/comment/response/PostCommentListResponseDto.java, src/main/java/cocodas/prier/board/post/post/Category.java, src/main/java/cocodas/prier/board/post/post/Post.java, src/main/java/cocodas/prier/board/post/post/PostService.java, src/test/java/cocodas/prier/PrierApplicationTests.java
* 게시판 댓글 기능 구현 및 일부 코드 수정 및 테스트 코드 삭제
* 게시판 댓글 기능 구현
* Post에 Category에 @Enumerated[(EnumType.STRING) 추가
* post builder에 user 추가할 때, user에 post에 자신 추가
* PostService에 TODO 작성해놨어용
* PostComment CRUD 구현한 거 봐주세용
=> chore: fix: feat: PostComment CRUD 구현 및 Post 일부 수정

src/main/java/cocodas/prier/point/PointTransaction.java, src/main/java/cocodas/prier/project/feedback/response/ResponseController.java
* Response에서 jwt 로 userId 받아오게 수정
*
*
=> refactor: Response에서 jwt 로 userId 받아오게 수정

src/main/java/cocodas/prier/board/comment/PostCommentController.java, src/main/java/cocodas/prier/project/feedback/response/ResponseRepository.java, src/main/java/cocodas/prier/quest/QuestController.java, src/main/java/cocodas/prier/quest/QuestService.java, src/main/java/cocodas/prier/user/kakao/KakaoService.java
* 오늘치 피드백이랑 댓글 확인해서 퀘스트 버튼 누르면 퀘스트 달성하게 구현
* 퀘스트 수행
* 연관된 레포지토리에 userId로 가져오게끔 구현
* 로그인할 때 createQuest 호출하게 구현
*
=> refactor: fix: feat: 2, 3번째 퀘스트 기능 구현

src/main/java/cocodas/prier/project/comment/ProjectCommentController.java, src/main/java/cocodas/prier/project/comment/ProjectCommentRepository.java, src/main/java/cocodas/prier/project/comment/ProjectCommentService.java
* 내 프로젝트 댓글 조회 기능 구현
* 내 프로젝트 댓글 조회 기능 구현
*
=> feat : 내 프로젝트 댓글 조회 기능 구현

src/main/java/cocodas/prier/board/post/PostController.java, src/main/java/cocodas/prier/board/post/post/PostRepository.java, src/main/java/cocodas/prier/board/post/post/PostService.java, src/main/java/cocodas/prier/board/post/post/response/PostResponseDto.java
* 조회 기능 추가함(검색어를 통한 조회 기능은 아직 수정중~)
* PostService, PostController, PostRepository
=> fix: feat: 게시글 CRUD 관련 조회 기능 추가

src/main/java/cocodas/prier/board/post/PostController.java, src/main/java/cocodas/prier/board/post/post/PostService.java, src/main/java/cocodas/prier/board/post/postmedia/PostMedia.java, src/main/java/cocodas/prier/board/post/postmedia/PostMediaService.java
* 게시글에 사진 추가 기능
* 게시글에 사진 추가 기능 구현
* PostMedia
*
=> feat: 게시글에 사진 추가 기능 구현

src/main/java/cocodas/prier/board/post/post/PostService.java, src/main/java/cocodas/prier/board/post/postmedia/PostMediaRepository.java, src/main/java/cocodas/prier/board/post/postmedia/PostMediaService.java
* 게시판 사진 수정, 삭제 시 DB에서는 삭제되지 않고 s3에서만 삭제됨.
* DB에서도 삭제되게 변경
*
=> fix: 게시판 사진 수정, 삭제 기능 오류 수정

src/main/java/cocodas/prier/board/post/PostController.java, src/main/java/cocodas/prier/board/post/post/PostService.java
* 키워드가 들어가 있는 게시글 찾는 기능 구현 완료
* PostService, PostController
=> fix: 키워드 검색하여 게시글 조회하기 기능 해결

src/main/java/cocodas/prier/board/post/PostController.java, src/main/java/cocodas/prier/board/post/like/LikeController.java, src/main/java/cocodas/prier/board/post/like/LikeRepository.java, src/main/java/cocodas/prier/board/post/like/LikeService.java, src/main/java/cocodas/prier/board/post/like/Likes.java, src/main/java/cocodas/prier/board/post/like/request/LikeRequestDto.java, src/main/java/cocodas/prier/board/post/post/Post.java, src/main/java/cocodas/prier/board/post/post/PostService.java, src/main/java/cocodas/prier/user/Users.java
* Likes 테이블이 추가됨으로써 Post 에 연관관계 수정
* Post
=> fix: Post 엔티티 연관관계 수정

src/main/java/cocodas/prier/product/ProductService.java, src/main/java/cocodas/prier/project/comment/ProjectCommentController.java, src/main/java/cocodas/prier/project/comment/ProjectCommentService.java, src/main/java/cocodas/prier/project/comment/dto/MyPageCommentDto.java, src/main/java/cocodas/prier/project/project/ProjectController.java, src/main/java/cocodas/prier/project/project/ProjectRepository.java, src/main/java/cocodas/prier/project/project/ProjectService.java, src/main/java/cocodas/prier/project/project/dto/MyPageProjectDto.java, src/main/java/cocodas/prier/project/project/dto/ProjectDetailDto.java, src/main/java/cocodas/prier/project/project/dto/ResponseDetailDto.java
*
* 내가 작성한 프로젝트 댓글 조회할 때 프론트한테 주는 내용 수정, 마이페이지에서 최근 프로젝트 조회하는 메소드 구현, 전체 프로젝트 조회랑 검색 메소드 합치고 전체 프로젝트 조회는 등록순, 인기순으로 정렬 및 페이징 가능
*
=> fix : 내가 작성한 프로젝트 댓글 조회, 마이페이지 최근 프로젝트 조회, 전체 프로젝트 조회 수정, 프로젝트 조회 시 페이징 구현

src/main/java/cocodas/prier/board/post/PostController.java, src/main/java/cocodas/prier/board/post/post/Post.java, src/main/java/cocodas/prier/board/post/post/PostService.java, src/main/java/cocodas/prier/board/post/post/response/PostDetailResponseDto.java, src/main/java/cocodas/prier/board/post/post/response/PostMediaDto.java, src/main/java/cocodas/prier/board/post/postmedia/PostMediaService.java
- 카테고리 검색 api 주소 변경
* 게시글 단건 조회 기능
* 게시글 조회수 기능
* 카테고리 검색 api 주소 변경
* 게시글 단건 조회 기능 추가
* 게시글 조회수 기능 추가
*
=> fix: feat: 게시글 단건 조회 기능 추가 + 게시글 조회수 기능 추가

src/main/java/cocodas/prier/board/post/PostController.java, src/main/java/cocodas/prier/board/post/post/PostService.java, src/main/java/cocodas/prier/board/post/post/response/PostListResponseDto.java
* dto 수정
* 미디어 파일 크기 조정 
* api 경로 수정
*
=> fix: dto 수정 + 미디어 파일 크기 조정 + api 경로 수정

src/main/java/cocodas/prier/project/feedback/response/ResponseController.java, src/main/java/cocodas/prier/project/feedback/response/dto/ResponseRequestDto.java
* 뒤죽 박죽인 주소들이 마음에 안 들었다. 
* ResponseController 수정
*
=> refactor: ResponseController 수정

src/main/java/cocodas/prier/board/comment/PostCommentController.java
* 댓글 Controller @PathVariable 경로 구체적으로 설정
*
*
=> fix: 댓글 Controller 수정

src/main/java/cocodas/prier/project/feedback/response/ResponseController.java, src/main/java/cocodas/prier/project/feedback/response/ResponseRepository.java, src/main/java/cocodas/prier/project/feedback/response/ResponseService.java, src/main/java/cocodas/prier/project/feedback/response/dto/UserResponseProjectDto.java
* 자신이 응답을 남긴 프로젝트 목록 조회 추가
*
*
=> feat: 자신이 응답을 남긴 프로젝트 목록 조회 추가

src/main/java/cocodas/prier/board/comment/PostCommentService.java, src/main/java/cocodas/prier/board/comment/response/PostCommentListResponseDto.java
* PostCommentListResponseDto에 commentId 추가
* PostCommentListResponseDto에 commentId 추가
*
=> fix: PostCommentListResponseDto에 commentId 추가

src/main/java/cocodas/prier/board/post/PostController.java, src/main/java/cocodas/prier/board/post/like/LikeRepository.java, src/main/java/cocodas/prier/board/post/like/LikeService.java, src/main/java/cocodas/prier/board/post/post/PostService.java, src/main/java/cocodas/prier/board/post/post/response/PostListResponseDto.java, src/main/java/cocodas/prier/config/SecurityConfig.java
* 게시글 목록 dto 수정(내가 좋아요 했는지 boolean 타입 리턴 + userId 추가)
* 좋아요 취소 구현
*
=> fix:feat: 전체 게시글 목록 dto 수정 + 좋아요 취소 구현

src/main/java/cocodas/prier/project/project/ProjectController.java, src/main/java/cocodas/prier/project/project/ProjectService.java
* 프로젝트 생성 시 null 값 비허용
* 프로젝트 생성 시 검증 후 빈 값 있으면 프론트에서 사용하도록 -1 반환
*
=> feat : 프로젝트 생성 시 검증 기능

src/main/java/cocodas/prier/project/feedback/question/QuestionController.java, src/main/java/cocodas/prier/project/feedback/question/QuestionService.java, src/main/java/cocodas/prier/project/project/ProjectController.java, src/main/java/cocodas/prier/project/project/ProjectService.java
*
* 프로젝트 질문은 삭제, 추가만 가능하도록 수정했고, 그에 따라서 질문 개별 삭제도 추가함. 질문 개별 삭제는 그 질문에 해당하는 응답까지 연쇄 삭제 됨.
*
=> fix : 프로젝트 질문 수정기능 제거, 피드백 개수 카운트 로직 변경, 질문 개별 삭제 추가

src/main/java/cocodas/prier/project/feedback/question/QuestionService.java, src/main/java/cocodas/prier/project/project/ProjectService.java
=> fix : 프로젝트 생성 수정

src/main/java/cocodas/prier/project/comment/ProjectCommentController.java, src/main/java/cocodas/prier/project/comment/ProjectCommentService.java, src/main/java/cocodas/prier/project/comment/dto/CommentDto.java, src/main/java/cocodas/prier/project/media/ProjectMediaService.java
=> fix : 댓글 조회시 isMine 필드 추가

src/main/java/cocodas/prier/point/kakao/KakaoPay.java, src/main/java/cocodas/prier/point/kakao/KakaoPayController.java, src/main/java/cocodas/prier/point/kakao/KakaoPayRepository.java, src/main/java/cocodas/prier/point/kakao/KakaoPayService.java, src/main/java/cocodas/prier/point/kakao/PayInfoDto.java, src/main/java/cocodas/prier/point/kakao/request/MakePayRequest.java, src/main/java/cocodas/prier/point/kakao/request/PayRequest.java, src/main/java/cocodas/prier/point/kakao/response/Amount.java, src/main/java/cocodas/prier/point/kakao/response/BaseResponse.java, src/main/java/cocodas/prier/point/kakao/response/PayApproveResDto.java, src/main/java/cocodas/prier/point/kakao/response/PayReadyResDto.java, src/main/java/cocodas/prier/project/project/ProjectController.java, src/main/java/cocodas/prier/user/Users.java
*
* 카카오페이 결제 기능 구현, 결제 로그 db 추가
*
=> feat : 카카오페이 결제 기능 구현, 결제 로그 DB 추가

src/main/java/cocodas/prier/project/project/ProjectController.java, src/main/java/cocodas/prier/project/project/ProjectService.java
* userId 받아서 프로젝트 조회 추가
* userId 받아서 프로젝트 조회 추가
* 나의 프로젝트 조회 일단 그냥 필요할 수도 있으니 남겨뒀음
* ProjectService 수정해서 다시 pr할 예정
=> chore: 유저 프로젝트 조회 추가

src/main/java/cocodas/prier/point/PointTransactionController.java, src/main/java/cocodas/prier/point/PointTransactionService.java, src/main/java/cocodas/prier/point/dto/PointPurchaseRequest.java, src/main/java/cocodas/prier/point/dto/PointRechargeRequest.java, src/main/java/cocodas/prier/point/dto/PointRequest.java
* 포인트 증가의 통합된 처리
* PointTransactionService에 POINT_PURCHASE, QUEST_REWARD를 통합하여 처리할 수 있도록 processPointIncreaseTransaction으로 변경
* point dto에 PointRequest를 추가하려 transactionType을 받고, PointPurchaseRequest, PointRechargeRequest에 각각 extends 추가
* 포인트 감소도 수정 예정
=> refactor: 포인트 증가의 통합된 처리

src/main/java/cocodas/prier/point/kakao/KakaoPayController.java, src/main/java/cocodas/prier/point/kakao/KakaoPayService.java, src/main/java/cocodas/prier/product/ProductService.java, src/main/java/cocodas/prier/project/comment/ProjectCommentController.java, src/main/java/cocodas/prier/project/comment/ProjectCommentService.java, src/main/java/cocodas/prier/project/comment/dto/CommentDto.java, src/main/java/cocodas/prier/project/project/ProjectController.java, src/main/java/cocodas/prier/project/project/ProjectService.java, src/main/java/cocodas/prier/project/project/dto/ProjectDetailForFeedbackPageDto.java
PointTransactionService에서 포인트 증가 기능 수정
* 포인트 차감 메소드 이름 바꾼거 수정, 댓글 조회할때 userId로 조회, 댓글 조회할때 userId 필드 추가, 한 번에 프론트에 보낼때 사용할 메소드 작성
*
=> fix : 포인트 차감 메소드 이름 바꾼거 수정, 댓글 조회할때 userId로 조회, 댓글 조회할때 userId 필드 추가

src/main/java/cocodas/prier/project/project/ProjectService.java
* ProjectService 고치는 걸 깜빡함
*
*
=> chore: 로깅 추가 및 ProjectService 수정

src/main/java/cocodas/prier/point/kakao/KakaoPayService.java
=> feat : 결제 완료시 사용자 계정에 포인트 추가

src/main/java/cocodas/prier/project/comment/ProjectCommentService.java, src/main/java/cocodas/prier/project/project/ProjectService.java
=> fix : 구분기호 추가

src/main/java/cocodas/prier/project/comment/ProjectCommentService.java, src/main/java/cocodas/prier/project/comment/dto/CommentDto.java
=> fix : 댓글 isMine 필드 수정

src/main/java/cocodas/prier/project/project/ProjectRepository.java, src/main/java/cocodas/prier/statics/objective/ObjectiveResponseController.java, src/main/java/cocodas/prier/statics/objective/ObjectiveResponseService.java
* 객관식 응답 통계 기능 구현
* 객관식 응답 통계 기능 구현하면서 n+1 문제가 발생해서 ProjectRepository에 Question이랑 Response 한 번에 가져올 수 있게 @EntityGraph로 구현
*
=> feat: 객관식 응답 통계 기능 구현

src/main/java/cocodas/prier/board/post/post/Post.java, src/main/java/cocodas/prier/point/kakao/KakaoPayController.java, src/main/java/cocodas/prier/point/kakao/KakaoPayService.java, src/main/java/cocodas/prier/point/kakao/request/MakePayRequest.java, src/main/java/cocodas/prier/point/pointTransaction/TransactionType.java
*
* 결제 수정, 포인트 환불 적용, 게시판 내용 글자 제한 수정
*
=> fix : 결제 수정, 포인트 환불 적용, 게시판 내용 글자 제한 수정

src/main/java/cocodas/prier/board/post/post/Post.java, src/main/java/cocodas/prier/board/post/post/PostService.java, src/main/java/cocodas/prier/board/post/post/request/PostRequestDto.java, src/main/java/cocodas/prier/board/post/post/response/PostMediaDto.java, src/main/java/cocodas/prier/board/post/postmedia/PostMedia.java, src/main/java/cocodas/prier/board/post/postmedia/PostMediaService.java, src/main/java/cocodas/prier/project/media/ProjectMediaService.java
*
게시글 수정시 이미지 처리 로직 수정, 프로젝트 메인이미지 없으면 Null 반환하도록 수정
*
=>  fix : 게시글 수정시 이미지 처리 로직 수정, 프로젝트 메인이미지 없으면 Null 반환하도록 수정

src/main/java/cocodas/prier/statics/chatgpt/ChatGPTController.java, src/main/java/cocodas/prier/statics/chatgpt/ChatGPTService.java, src/main/java/cocodas/prier/statics/chatgpt/request/ChatGPTRequest.java, src/main/java/cocodas/prier/statics/chatgpt/response/ChatGPTResponse.java, src/main/java/cocodas/prier/statics/chatgpt/response/SummaryResponse.java
* chatGPT 사용해서 피드백 요약하는 기능 구현
* chatGPT 사용해서 피드백 요약하는 기능 구현
*
=> feat: chatGPT 사용해서 피드백 요약하는 기능 구현

src/main/java/cocodas/prier/board/comment/PostCommentService.java, src/main/java/cocodas/prier/board/comment/response/PostCommentListResponseDto.java, src/main/java/cocodas/prier/board/post/post/PostService.java, src/main/java/cocodas/prier/board/post/post/response/PostDetailResponseDto.java
* 특정 게시글 보기에 내가 좋아요 누른 글인지 확인 + 닉네임 추가
* 특정 게시글 보기에 내가 좋아요 누른 글인지 확인 + 닉네임 추가
*
=> fix: 특정 게시글 보기에 내가 좋아요 누른 글인지 확인 + 닉네임 추가

src/main/java/cocodas/prier/board/post/post/PostService.java, src/main/java/cocodas/prier/project/media/ProjectMediaService.java, src/main/java/cocodas/prier/project/media/dto/ProjectMediaDto.java, src/main/java/cocodas/prier/project/project/ProjectService.java, src/main/java/cocodas/prier/project/project/dto/ProjectForm.java
=> fix : 프로젝트 이미지 업데이트 수정

src/main/java/cocodas/prier/project/feedback/response/ResponseController.java, src/main/java/cocodas/prier/project/feedback/response/ResponseService.java, src/main/java/cocodas/prier/project/feedback/response/dto/ResponseDetailDto.java, src/main/java/cocodas/prier/project/feedback/response/dto/ResponseObjectiveDto.java
* 프로젝트 응답 상세보기
* 프로젝트 응답 상세보기
*
=> fix: 프로젝트 응답 상세보기

src/main/java/cocodas/prier/point/kakao/request/MakePayRequest.java, src/main/java/cocodas/prier/project/project/ProjectService.java
프로젝트 응답 상세보기
내 최신 프로젝트 조회할때 없으면 null 반환하도록 수정
*
=> fix : 내 최신 프로젝트 조회할때 없으면 null 반환하도록 수정

src/main/java/cocodas/prier/user/UserService.java
* 마이페이지에서 project null일 때 관련된 내용 다 null로 보내게 수정
* 마이페이지에서 project null일 때 관련된 내용 다 null로 보내게 수정
*
=> fix: 마이페이지에서 project null일 때 관련된 내용 다 null로 보내게 수정

src/main/java/cocodas/prier/quest/QuestController.java, src/main/java/cocodas/prier/quest/QuestService.java
* 퀘스트 예외 발생 시 예외를 던지는게 아니라 string으로 보내게 수정
* 퀘스트 예외 발생 시 예외를 던지는게 아니라 string으로 보내게 수정
*
=> fix: 퀘스트 예외 발생 시 예외를 던지는게 아니라 string으로 보내게 수정

src/main/java/cocodas/prier/project/feedback/response/ResponseController.java, src/main/java/cocodas/prier/project/feedback/response/ResponseService.java, src/main/java/cocodas/prier/user/Users.java, src/main/java/cocodas/prier/user/kakao/KakaoService.java
* 로그인 시 마지막 로그인 시간 저장 안되는거 되게 수정, 로그인 시 퀘스트 기능 수정
* 로그인 시 마지막 로그인 시간 저장 안되는거 되게 수정
* 로그인 시 퀘스트 기능 수정
*새로운 사용자에게만 퀘스트 생성하는거였는데 기존 사용자가 로그인했을 때 오늘 날짜의 퀘스트가 없다면 그때도 생성해야 한다.
*
=> refactor: fix: 로그인 시 마지막 로그인 시간 저장 안되는거 되게 수정, 로그인 시 퀘스트 기능 수정

src/main/java/cocodas/prier/point/kakao/request/MakePayRequest.java, src/main/java/cocodas/prier/project/project/ProjectService.java, src/main/java/cocodas/prier/project/project/dto/ProjectDto.java
유저 프로젝트 조회할때 개발 시작일, 상태 추가, 최근 프로젝트 조회할때 점수 올바르게 가도록 수정
유저 프로젝트 조회할때 개발 시작일, 상태 추가, 최근 프로젝트 조회할때 점수 올바르게 가도록 수정
*
=> fix : 유저 프로젝트 조회할때 개발 시작일, 상태 추가, 최근 프로젝트 조회할때 점수 올바르게 가도록 수정

src/main/java/cocodas/prier/project/project/ProjectService.java, src/main/java/cocodas/prier/project/project/dto/ProjectDto.java
=> fix : 유저 프로젝트 조회시 배포 링크 추가

src/main/java/cocodas/prier/project/comment/ProjectCommentRepository.java, src/main/java/cocodas/prier/project/comment/ProjectCommentService.java, src/main/java/cocodas/prier/project/project/ProjectController.java
마지막 로그인 이후 내 프로젝트에 달린 댓글 수 리턴하는 메소드 구현
*
=> feat : 마지막 로그인 이후 내 프로젝트에 달린 댓글 수 리턴하는 메소드 구현

src/main/java/cocodas/prier/user/UserController.java, src/main/java/cocodas/prier/user/UserService.java, src/main/java/cocodas/prier/user/Users.java, src/main/java/cocodas/prier/user/dto/request/EmailRequestDto.java
* User가 마이페이지에서 이메일 수정할 수 있음
* User가 마이페이지에서 이메일 수정할 수 있음
*
=> feat: 이메일 수정하기 기능 추가하기

src/main/java/cocodas/prier/board/post/postmedia/PostMediaService.java
* 게시판에서 게시글 볼 때, post_media_id 가 작은수부터 응답 보내기
* 게시판에서 게시글 볼 때, post_media_id 가 작은수부터 응답 보내기
=> fix: 게시글에서 사진 가져올 때 post_media_id 가 작은 순부터 응답 보내기

src/main/java/cocodas/prier/user/dto/request/EmailRequestDto.java
=> fix: 이메일 수정하기

.gitignore, docker-compose.yml, dockerfile, src/main/java/cocodas/prier/project/project/ProjectService.java
* ec2에서 docker 이용해서 실행
* dockerfile 및 docker-compose 파일 작성
*
=> ci : dockerfile 및 docker-compose 파일 작성

src/main/java/cocodas/prier/project/comment/ProjectCommentService.java, src/main/java/cocodas/prier/user/UserService.java, src/main/java/cocodas/prier/user/dto/NotificationDto.java
*
* UserService에 알림에 필요한 응답, 댓글 수 리턴하는 메소드 구현
*
=> feat : UserService에 알림에 필요한 응답, 댓글 수 리턴하는 메소드 구현

src/main/java/cocodas/prier/point/kakao/request/MakePayRequest.java, src/main/java/cocodas/prier/project/project/ProjectController.java
=> fix : 카카오 결제 주소 수정

src/main/java/cocodas/prier/point/kakao/request/MakePayRequest.java, src/main/java/cocodas/prier/project/project/Project.java, src/main/java/cocodas/prier/project/project/ProjectController.java, src/main/java/cocodas/prier/project/project/ProjectService.java
=> fix : 프로젝트별 계산된 평점 필드 추가

src/main/java/cocodas/prier/board/post/post/PostService.java, src/main/java/cocodas/prier/board/post/post/response/PostDetailResponseDto.java, src/main/java/cocodas/prier/board/post/post/response/PostListResponseDto.java, src/main/java/cocodas/prier/project/feedback/response/ResponseService.java, src/main/java/cocodas/prier/project/feedback/response/dto/ResponseDetailDto.java, src/main/java/cocodas/prier/user/UserController.java, src/main/java/cocodas/prier/user/UserService.java, src/main/java/cocodas/prier/user/Users.java, src/main/java/cocodas/prier/user/dto/response/LoginSuccessResponse.java, src/main/java/cocodas/prier/user/kakao/KakaoService.java, src/main/java/cocodas/prier/user/response/ProfileImgDto.java
* 프로필 이미지 수정 + 프로필 이미지 기본값 조회하기 + 개인 알림 서비스
* UserService, ResponseService, 응답 Dto 들
*
=> fix: 프로필 이미지 수정 + 프로필 이미지 기본값 조회하기 + 개인 알림 서비스

src/main/java/cocodas/prier/project/comment/ProjectCommentService.java, src/main/java/cocodas/prier/project/comment/dto/CommentDto.java, src/main/java/cocodas/prier/project/project/Project.java, src/main/java/cocodas/prier/project/project/ProjectService.java, src/main/java/cocodas/prier/user/UserService.java
프로필 이미지 수정 + 프로필 이미지 기본값 조회하기 + 개인 알림 서비스
인기순 수정, 댓글 조회시 프로필 사진도 넘겨줌
*
=> fix : 인기순 수정, 댓글 조회시 프로필 사진도 넘겨줌

src/main/java/cocodas/prier/project/comment/ProjectCommentService.java, src/main/java/cocodas/prier/user/UserProfileService.java, src/main/java/cocodas/prier/user/UserService.java
프로필 이미지 수정 + 프로필 이미지 기본값 조회하기 + 개인 알림 서비스
유저 서비스, 프로젝트 댓글 순환참조 해결
*
=> fix : 유저 서비스, 프로젝트 댓글 순환참조 해결

src/main/java/cocodas/prier/project/feedback/response/ResponseService.java, src/main/java/cocodas/prier/project/feedback/response/dto/ResponseDetailDto.java, src/main/java/cocodas/prier/user/UserProfileService.java, src/main/java/cocodas/prier/user/UserService.java, src/main/java/cocodas/prier/user/Users.java, src/main/java/cocodas/prier/user/response/MyPageResponseDto.java
* 프로젝트 피드백 상세보기 dto 수정 및 기본 프로필 이미지 수정
* 프로젝트 피드백 상세보기 dto 수정 및 기본 프로필 이미지 수정
*
=> fix: 프로젝트 피드백 상세보기 dto 수정 및 기본 프로필 이미지 수정

src/main/java/cocodas/prier/point/kakao/request/MakePayRequest.java, src/main/java/cocodas/prier/project/comment/ProjectCommentRepository.java, src/main/java/cocodas/prier/project/comment/ProjectCommentService.java, src/main/java/cocodas/prier/project/feedback/response/ResponseService.java
=> fix : 마지막 로그인 알림 댓글 수정

src/main/java/cocodas/prier/user/kakao/KakaoService.java
* lastLoginAt 수정을 알림 dto 가져온 후로 변경
* lastLoginAt 수정을 알림 dto 가져온 후로 변경
*
=> fix: lastLoginAt 수정을 알림 dto 가져온 후로 변경

src/main/java/cocodas/prier/project/project/ProjectService.java
=> fix : 로그 제거

src/main/java/cocodas/prier/project/comment/ProjectCommentController.java, src/main/java/cocodas/prier/project/comment/ProjectCommentService.java, src/main/java/cocodas/prier/project/comment/dto/CommentWithProfileDto.java, src/main/java/cocodas/prier/project/feedback/response/ResponseService.java, src/main/java/cocodas/prier/project/feedback/response/dto/ResponseDetailDto.java, src/main/java/cocodas/prier/project/feedback/response/dto/ResponseObjectiveDto.java, src/main/java/cocodas/prier/statics/chatgpt/ChatGPTService.java, src/main/java/cocodas/prier/statics/chatgpt/response/SummaryResponse.java
* 상세 응답 분석에 대해 질문 ID, 질문 내용 추가
* 해당 프로젝트 댓글이 아닌 댓글도 나왔는데 이 부분도 수정
* 댓글 작성자의 프로필 보여주기
* 프로젝트의 평점(score) 보여주기
* 각 질문에 달린 응답 개수 보여주기
* 상세 응답 분석에 대해 질문 ID, 질문 내용 추가
* 해당 프로젝트 댓글이 아닌 댓글도 나왔는데 이 부분도 수정
* 댓글 작성자의 프로필 보여주기
* 프로젝트의 평점(score) 보여주기
* 각 질문에 달린 응답 개수 보여주기
=> fix: 프로젝트 피드백 상세보기 페이지에 대한 기능 전체적으로 수정

src/main/java/cocodas/prier/user/UserProfileService.java, src/main/java/cocodas/prier/user/UserService.java, src/main/java/cocodas/prier/user/Users.java
* 프로필 이미지 가져오기 기능 수정
* 프로필 이미지 가져오기 기능 수정
*
=> fix: 프로필 이미지 가져오기 기능 수정

src/main/java/cocodas/prier/board/post/post/Post.java, src/main/java/cocodas/prier/board/post/post/PostService.java, src/main/java/cocodas/prier/board/post/post/request/PostRequestDto.java, src/main/java/cocodas/prier/board/post/post/response/PostMediaDto.java, src/main/java/cocodas/prier/board/post/postmedia/PostMedia.java, src/main/java/cocodas/prier/board/post/postmedia/PostMediaService.java
* 게시글 수정하기 오류 고침
* 게시글 수정하기 오류 고침
*
=> fix: 게시글 수정하기 오류 고침

src/main/java/cocodas/prier/project/feedback/response/ResponseController.java, src/main/java/cocodas/prier/project/feedback/response/ResponseService.java
* 질문별 응답조회 기능 추가
* response 컨트롤러 및 서비스 수정
*
=> feat: 질문별 응답 조회

src/main/java/cocodas/prier/board/comment/PostCommentRepository.java, src/main/java/cocodas/prier/project/comment/ProjectCommentRepository.java, src/main/java/cocodas/prier/quest/QuestService.java, src/main/java/cocodas/prier/user/UserController.java, src/main/java/cocodas/prier/user/UserService.java
* 이메일 삭제 못하게 수정, 마이페이지에서 내가 쓴 프로젝트 댓글 가져오게 수정, 2번째 퀘스트 되게 수정
* 이메일 삭제 못하게 수정, 마이페이지에서 내가 쓴 프로젝트 댓글 가져오게 수정, 2번째 퀘스트 되게 수정
*
=> fix: 이메일 삭제 못하게 수정, 마이페이지에서 내가 쓴 프로젝트 댓글 가져오게 수정, 2번째 퀘스트 되게 수정

src/main/java/cocodas/prier/board/post/PostController.java, src/main/java/cocodas/prier/board/post/post/PostService.java, src/main/java/cocodas/prier/board/post/post/response/PostListResponseDto.java, src/main/java/cocodas/prier/board/post/post/response/PostResponseDto.java, src/main/java/cocodas/prier/board/post/postmedia/PostMediaService.java, src/main/java/cocodas/prier/user/UserController.java
* 게시글 리스트 dto 수정
* 게시글 리스트 dto 수정
*
=> fix: 게시글 리스트 dto 수정

src/main/java/cocodas/prier/board/comment/PostCommentService.java, src/main/java/cocodas/prier/board/comment/response/PostCommentListResponseDto.java, src/main/java/cocodas/prier/board/post/post/PostService.java, src/main/java/cocodas/prier/board/post/post/response/PostDetailResponseDto.java
* 게시글 상세 조회하기 dto 수정 - 작성자 프로필 url 추가
* 게시글 상세 조회하기 dto 수정 - 작성자 프로필 url 추가
*
=> fix: 게시글 상세 조회하기 dto 수정 - 작성자 프로필 url 추가

src/main/java/cocodas/prier/point/kakao/request/MakePayRequest.java, src/main/java/cocodas/prier/project/project/ProjectService.java, src/main/java/cocodas/prier/project/project/dto/ProjectDto.java
프로젝트 조회시 프로필 사진도 주도록 변경
프로젝트 조회시 프로필 사진도 주도록 변경
*
=> fix : 프로젝트 조회시 프로필 사진도 주도록 변경

src/main/java/cocodas/prier/project/project/ProjectService.java, src/main/java/cocodas/prier/project/project/dto/ProjectDetailDto.java
프로젝트 상세보기에 프로필 사진 추가
프로젝트 상세보기에 프로필 사진 추가
*
=> fix : 프로젝트 상세보기에 프로필 사진 추가

docker-compose.yml, dockerfile, src/main/java/cocodas/prier/user/UserController.java, src/main/java/cocodas/prier/user/UserService.java, src/main/java/cocodas/prier/user/response/OhterMyPageResponseDto.java
* 다른 사람의 마이페이지 조회하기에서 남의 프로필 사진 추가
* 다른 사람의 마이페이지 조회하기에서 남의 프로필 사진 추가
*
=> fix: 다른 사람의 마이페이지 조회하기에서 남의 프로필 사진 추가

src/main/java/cocodas/prier/project/comment/ProjectCommentRepository.java, src/main/java/cocodas/prier/project/comment/ProjectCommentService.java, src/main/java/cocodas/prier/project/feedback/response/ResponseRepository.java, src/main/java/cocodas/prier/project/feedback/response/ResponseService.java, src/main/java/cocodas/prier/user/UserController.java, src/main/java/cocodas/prier/user/UserService.java, src/main/java/cocodas/prier/user/Users.java, src/main/java/cocodas/prier/user/dto/request/LogoutRequest.java, src/main/java/cocodas/prier/user/kakao/KakaoService.java
* 마지막 로그아웃 시점 저장하기
* 마지막 로그아웃 시점 저장하기
*
=> fix: 사용자가 로그아웃하거나 페이지를 벗어나면 마지막 로그아웃 시간 보내서 저장하는 기능

docker-compose.yml, src/main/java/cocodas/prier/config/SecurityConfig.java, src/main/java/cocodas/prier/user/kakao/KakaoController.java
=> fix: 프론트 CORS 설정

docker-compose.yml, src/main/java/cocodas/prier/config/SecurityConfig.java, src/main/java/cocodas/prier/user/UserController.java, src/main/java/cocodas/prier/user/kakao/KakaoController.java, src/main/java/cocodas/prier/user/kakao/KakaoService.java
=> fix: 카카오 로그인 log 찍기

src/main/java/cocodas/prier/quest/QuestService.java
*  퀘스트하면 코어 증가
* 퀘스트하면 코어 증가
*
=> fix: 퀘스트하면 코어 증가

src/main/java/cocodas/prier/point/kakao/KakaoPayController.java, src/main/java/cocodas/prier/point/kakao/request/MakePayRequest.java, src/main/java/cocodas/prier/user/kakao/KakaoController.java
=> fix : localhost로 임시변경

src/main/java/cocodas/prier/project/project/ProjectController.java, src/main/java/cocodas/prier/project/project/ProjectService.java, src/main/java/cocodas/prier/project/project/dto/ProjectDto.java
projectDto에 isMine 필드 추가
projectDto에 isMine 필드 추가
*
=> fix : projectDto에 isMine 필드 추가

src/main/java/cocodas/prier/board/post/PostController.java, src/main/java/cocodas/prier/board/post/post/PostService.java, src/main/java/cocodas/prier/config/SecurityConfig.java, src/main/java/cocodas/prier/user/UserService.java, src/main/java/cocodas/prier/user/Users.java
* 게시판 좋아요 수정
* 게시판 좋아요 수정(PostController, PostService)
*
=> fix: 게시판 좋아요 수정

src/main/java/cocodas/prier/point/kakao/KakaoPayController.java, src/main/java/cocodas/prier/point/kakao/request/MakePayRequest.java, src/main/java/cocodas/prier/project/project/ProjectService.java, src/main/java/cocodas/prier/project/project/dto/ProjectDto.java
projectDto에 userId 필드 추가
projectDto에 userId 필드 추가
*
=> fix : projectDto에 userId 필드 추가
